networks:
  gemini:

services:
      grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        env_file:
            - .env
        volumes:
            - grafana-storage:/var/lib/grafana
        depends_on:
            - influxdb
        restart: unless-stopped
        networks:
            - gemini

      mysqldb:
        image: mysql:8.0
        ports:
          - 3306:3306
        env_file:
          - .env
        volumes:
          - mysqldb_data-storage:/data/db
          - mysqldb_var_lib-storage:/var/lib/mysql
        restart: unless-stopped
        networks:
          - gemini

      influxdb:
        image: influxdb:latest
        ports:
          - 8086:8086
          - 8998:8088
        env_file:
          - .env
        volumes:
          - influxdb-storage:/var/lib/influxdb
          - influxdb2-storage:/var/lib/influxdb2
          - influxdb2etc-storage:/etc/influxdb2
        restart: unless-stopped
        networks:
          - gemini

      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        env_file:
          - .env
        volumes:
          - redis-storage:/data
        restart: unless-stopped
        networks:
          - gemini

      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env_file:
          - .env
        volumes:
          - mongo-storage:/data/db
          - mongo-config:/data/configdb
        restart: unless-stopped
        networks:
          - gemini
            
      chromadb:
        image: chromadb/chroma
        ports:
          - 8000:8000
        env_file:
          - .env
        networks:
          - gemini
        volumes:
          - chroma-data:/data
        restart: unless-stopped

      ollama:
        container_name: ollama
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        env_file:
          - .env
        volumes:
          - ollama_data:/root/.ollama
        restart: unless-stopped
        networks:
          - gemini
        command: serve

volumes:
  mysqldb_data-storage:
  mysqldb_var_lib-storage:
  grafana-storage:
  influxdb-storage:
  influxdb2-storage:
  influxdb2etc-storage:
  mongo-storage:
  mongo-config:
  chroma-data:
  ollama_data:
  redis-storage:
