{
 "title": "ESP Monitoring",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "buckets()\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"_value\"})\n  |> sort(columns: [\"_value\"])"
   },
   {
    "name": "measurement",
    "label": "Measurement",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"${bucket}\", start: -3650d)\n  |> sort(columns: [\"_value\"])"
   },
   {
    "name": "asset_name",
    "label": "ESP Asset",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"${bucket}\",\n  tag: \"asset_name\",\n  predicate: (r) => r._measurement == \"${measurement}\" and r.asset_name =~ /^esp_.*/,\n  start: -3650d\n)\n  |> sort(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "ESP Pressure",
   "type": "timeseries",
   "description": "Showing ESP intake pressure and discharge pressure in Bar",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_inlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_outlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ESP Temperature",
   "type": "timeseries",
   "description": "Showing ESP intake temperature in C",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_inlet_temperature.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ESP Voltage",
   "type": "timeseries",
   "description": "Showing ESP voltage in Volt",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_voltage.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ESP Current",
   "type": "timeseries",
   "description": "Showing ESP current in Ampere",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_current.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ESP Flow",
   "type": "timeseries",
   "description": "Showing ESP flow in m3/h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_flow.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ESP Frequency",
   "type": "timeseries",
   "description": "Showing ESP frequency in Hz",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${asset_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"esp_frequency.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  }
 ]
}