{
 "title": "Injection Pump",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "injection_pump_name",
    "label": "Injection Pump Name",
    "query": "injection_pump_a0bb,injection_pump_7578"
   }
  ]
 },
 "panels": [
  {
   "title": "Injection Pump Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${injection_pump_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionpump_inlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${injection_pump_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionpump_outlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Injection Pump Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${injection_pump_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionpump_frequency.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Injection Pump Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${injection_pump_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionpump_current.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Injection Pump Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"${injection_pump_name}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionpump_voltage.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  }
 ]
}