{
 "title": "Other assets",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Degasser Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"degasser_480f\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"degasser_inlet_flow.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Degasser Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"degasser_480f\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"degasser_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Boiler Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"gas_boiler_75e9\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"gasboiler_heat_pipe_inlet_temperature.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"gas_boiler_75e9\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"gasboiler_heat_pipe_outlet_temperature.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Filter Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"filter_4b6d\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"filter_inlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"filter_4b6d\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"filter_outlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"filter_54d6\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"filter_inlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"filter_54d6\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"filter_outlet_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Well Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"production_well_067d\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"productionwell_wellhead_temperature.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"injection_well_597f\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"injectionwell_wellhead_temperature.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Well Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"gemini-project\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"HAL\")\r\n|> filter(fn: (r) => r[\"asset_name\"] == \"production_well_067d\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"productionwell_wellhead_pressure.measured\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"mean\")"
    }
   ]
  }
 ]
}