# This workflow builds the Sphinx documentation and publishes it to GitHub Pages
# For more information see: https://docs.github.com/en/pages

name: Docs

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        ./ci/linux/run_installation.sh
    - name: Build documentation
      env:
        DOCS_VERSION: ${{ github.ref_name }}
      run: |
        poetry run sphinx-build -M html ./src/gemini_documentation/source ./src/gemini_documentation/build --fail-on-warning
    - name: Compute docs destination
      id: docs_destination
      shell: bash
      run: |
        BRANCH="${GITHUB_REF_NAME}"
        SAFE_BRANCH="${BRANCH//\//-}"
        echo "destination=${SAFE_BRANCH}" >> "$GITHUB_OUTPUT"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/gemini_documentation/build/html
        destination_dir: ${{ steps.docs_destination.outputs.destination }}
        keep_files: true
